import {
  css,
  excel,
  html,
  img1,
  img2,
  img3,
  nodeJs,
  photoshop,
  powerPoint,
  python,
  word,
} from "@/assets/icons";

export const profileInfo = [
  "Core Skills & Technical Proficiencies",
  "Professional Journey & Internship Roles",
  "Case Insights & Key Projects",
  "Learning & Academic Milestones",
  "Endorsements from Mentors & Peers",
];

export const skills = [
  photoshop,
  nodeJs,
  html,
  css,
  python,
  excel,
  word,
  powerPoint,
];

export const cases = [
  {
    title: "ONDC Case Study",
    img: img1,
  },
  {
    title: "Jal Jeevan Mission Case Study",
    img: img2,
  },
  {
    title: "FinEasy Case Study",
    img: img3,
  },
];

export const profiles = [
  {
    id: "1",
    name: "Aarav Sharma",
    avatar:
      "https://images.pexels.com/photos/262391/pexels-photo-262391.jpeg?_gl=1*1cxj2x5*_ga*MjI0ODA0MzUwLjE3NDM1MzI3NjM.*_ga_8JE65Q40S6*czE3NzA2Mzc1NDQkbzgkZzEkdDE3NzA2Mzc1NjQkajQwJGwwJGgw",
    gender: "Male",
    age: 25,
    pronouns: "He/Him",
    bio: "Frontend Developer",
    email: "aarav@example.com",
    phone: "+91 9876543210",
    location: "Bangalore, India",
    skills: ["React", "Next.js", "Tailwind"],
    experience: "2 Years",
  },
  {
    id: "2",
    name: "Neha Verma",
    avatar:
      "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?_gl=1*14qhzqj*_ga*MjI0ODA0MzUwLjE3NDM1MzI3NjM.*_ga_8JE65Q40S6*czE3NzA2Mzc1NDQkbzgkZzEkdDE3NzA2Mzc1ODgkajE2JGwwJGgw",
    gender: "Female",
    age: 27,
    pronouns: "She/Her",
    bio: "Backend Developer",
    email: "neha@example.com",
    phone: "+91 9123456780",
    location: "Delhi, India",
    skills: ["Node.js", "Express", "MongoDB"],
    experience: "3 Years",
  },
  {
    id: "3",
    name: "Rohit Patel",
    avatar:
      "https://images.pexels.com/photos/874158/pexels-photo-874158.jpeg?_gl=1*1it31zj*_ga*MjI0ODA0MzUwLjE3NDM1MzI3NjM.*_ga_8JE65Q40S6*czE3NzA2Mzc1NDQkbzgkZzEkdDE3NzA2Mzc2MDkkajYwJGwwJGgw",
    gender: "Male",
    age: 29,
    pronouns: "He/Him",
    bio: "Full Stack Developer",
    email: "rohit@example.com",
    phone: "+91 9988776655",
    location: "Ahmedabad, India",
    skills: ["MERN", "AWS", "Docker"],
    experience: "4 Years",
  },
  {
    id: "4",
    name: "Priya Singh",
    avatar:
      "https://images.pexels.com/photos/1065084/pexels-photo-1065084.jpeg?_gl=1*1a57kge*_ga*MjI0ODA0MzUwLjE3NDM1MzI3NjM.*_ga_8JE65Q40S6*czE3NzA2Mzc1NDQkbzgkZzEkdDE3NzA2Mzc2MzUkajM0JGwwJGgw",
    gender: "Female",
    age: 24,
    pronouns: "She/Her",
    bio: "UI/UX Designer",
    email: "priya@example.com",
    phone: "+91 9012345678",
    location: "Pune, India",
    skills: ["Figma", "Adobe XD", "UX Research"],
    experience: "1.5 Years",
  },
  {
    id: "5",
    name: "Karan Mehta",
    avatar:
      "https://images.pexels.com/photos/819530/pexels-photo-819530.jpeg?_gl=1*1xc74ir*_ga*MjI0ODA0MzUwLjE3NDM1MzI3NjM.*_ga_8JE65Q40S6*czE3NzA2Mzc1NDQkbzgkZzEkdDE3NzA2Mzc2NTUkajE0JGwwJGgw",
    gender: "Male",
    age: 31,
    pronouns: "He/Him",
    bio: "DevOps Engineer",
    email: "karan@example.com",
    phone: "+91 9345678123",
    location: "Mumbai, India",
    skills: ["AWS", "Docker", "Kubernetes"],
    experience: "6 Years",
  },
  {
    id: "6",
    name: "Ananya Rao",
    avatar:
      "https://images.pexels.com/photos/35119824/pexels-photo-35119824.jpeg?_gl=1*141dc0l*_ga*MjI0ODA0MzUwLjE3NDM1MzI3NjM.*_ga_8JE65Q40S6*czE3NzA2Mzc1NDQkbzgkZzEkdDE3NzA2Mzc2NzkkajU5JGwwJGgw",
    gender: "Female",
    age: 26,
    pronouns: "She/Her",
    bio: "Data Analyst",
    email: "ananya@example.com",
    phone: "+91 9765432189",
    location: "Hyderabad, India",
    skills: ["Python", "SQL", "Power BI"],
    experience: "2.5 Years",
  },
  {
    id: "7",
    name: "Vikram Joshi",
    avatar:
      "https://images.pexels.com/photos/1212984/pexels-photo-1212984.jpeg?_gl=1*9jisme*_ga*MjI0ODA0MzUwLjE3NDM1MzI3NjM.*_ga_8JE65Q40S6*czE3NzA2Mzc1NDQkbzgkZzEkdDE3NzA2Mzc3MDkkajI5JGwwJGgw",
    gender: "Male",
    age: 34,
    pronouns: "He/Him",
    bio: "Engineering Manager",
    email: "vikram@example.com",
    phone: "+91 9098765432",
    location: "Noida, India",
    skills: ["Leadership", "Agile", "System Design"],
    experience: "9 Years",
  },
  {
    id: "8",
    name: "Sneha Kulkarni",
    avatar:
      "https://images.pexels.com/photos/3760856/pexels-photo-3760856.jpeg?_gl=1*9jisme*_ga*MjI0ODA0MzUwLjE3NDM1MzI3NjM.*_ga_8JE65Q40S6*czE3NzA2Mzc1NDQkbzgkZzEkdDE3NzA2Mzc3MDkkajI5JGwwJGgw",
    gender: "Female",
    age: 23,
    pronouns: "She/Her",
    bio: "QA Engineer",
    email: "sneha@example.com",
    phone: "+91 9887766554",
    location: "Nagpur, India",
    skills: ["Manual Testing", "Cypress", "Jest"],
    experience: "1 Year",
  },
  {
    id: "9",
    name: "Arjun Malhotra",
    avatar:
      "https://images.pexels.com/photos/13043158/pexels-photo-13043158.jpeg?_gl=1*157tycr*_ga*MjI0ODA0MzUwLjE3NDM1MzI3NjM.*_ga_8JE65Q40S6*czE3NzA2Mzc1NDQkbzgkZzEkdDE3NzA2Mzc3MDkkajI5JGwwJGgw",
    gender: "Male",
    age: 28,
    pronouns: "He/Him",
    bio: "Mobile App Developer",
    email: "arjun@example.com",
    phone: "+91 9321456780",
    location: "Chandigarh, India",
    skills: ["React Native", "Flutter", "Firebase"],
    experience: "4 Years",
  },
  {
    id: "10",
    name: "Isha Kapoor",
    avatar:
      "https://images.pexels.com/photos/1090387/pexels-photo-1090387.jpeg?_gl=1*157tycr*_ga*MjI0ODA0MzUwLjE3NDM1MzI3NjM.*_ga_8JE65Q40S6*czE3NzA2Mzc1NDQkbzgkZzEkdDE3NzA2Mzc3MDkkajI5JGwwJGgw",
    gender: "Female",
    age: 30,
    pronouns: "She/Her",
    bio: "Product Manager",
    email: "isha@example.com",
    phone: "+91 9456123789",
    location: "Gurgaon, India",
    skills: ["Product Strategy", "Roadmapping", "Analytics"],
    experience: "5 Years",
  },
];
